#!/bin/bash
set -ex

# -------------------------------------------------------------------
# Clone and build MAIA
# -------------------------------------------------------------------
git clone --depth 1 https://github.com/onera/Maia.git
cd Maia
git submodule update --init

mkdir -p build
cd build

source /srv/conda/etc/profile.d/conda.sh
conda activate notebook

# Explicitly locate system libraries
export PARMETIS_ROOT=/usr         # System ParMETIS
export PTSCOTCH_ROOT=/usr         # System PT-Scotch
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu

cmake ../ \
  -DCMAKE_INSTALL_PREFIX="../Dist" \
  -DCMAKE_C_COMPILER=$(which mpicc) \
  -DCMAKE_CXX_COMPILER=$(which mpicxx) \
  -DCMAKE_CXX_STANDARD=17 \
  -DPython_EXECUTABLE=$(which python) \
  -DPython3_NumPy_INCLUDE_DIRS=$(python -c "import numpy; print(numpy.get_include())") \
  -DCMAKE_BUILD_TYPE=Release

make -j
make install

# Add to Python path
echo "export PYTHONPATH=\"\$PYTHONPATH:$(pwd)/../Dist/lib\"" >> ~/.bashrc
