#!/bin/bash
# Set environment variables for parallel HDF5/h5py
export CC=mpicc
export HDF5_MPI="ON"

# Source MAIA environment if available
if [ -f "/home/jovyan/Maia/build/source.sh" ]; then
  source /home/jovyan/Maia/build/source.sh
fi

# Create Directory cible
mkdir -p /stck/jcoulet/Public/maia_training/MESHES

# Move .gz files into directory
mv *.gz /stck/jcoulet/Public/maia_training/MESHES/

cd /stck/jcoulet/Public/maia_training/MESHES/

# Decompression.gz files
gzip -d *.gz

exec "$@"
